version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./applications/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://crm_user:c7fw63jd32aw3@postgres:5432/crm
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./applications/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
