version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: c7fw63jd32aw3
      POSTGRES_DB: crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./applications/backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: c7fw63jd32aw3
      DATABASE_USERNAME: crm_user
      DATABASE_NAME: crm
      JWT_SECRET: 57e231b741d2f541
    volumes:
      - ./applications/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./applications/frontend
    depends_on:
      - backend
    ports:
      - "5177:80"

volumes:
  postgres_data:
