version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: c7fw63jd32aw3
      POSTGRES_DB: crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./applications/backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./applications/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./applications/frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
